name: flame_coroutines
description: "Exploring the use of dart_coroutines with Flame"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  coroutines: 0.2.0
  flame: 1.33.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
